### ISSUE TITLE
[3pt] Crear Planilla de pintura

### ISSUE THREAD

**Issue by ramirocanario1** [UNPSJB/TallerChaPin#15]
**Como** Oficial Pintor **quiero** crear una planilla de pintura **para** asociar a un detalle de una orden de trabajo.

### Datos
Número de orden [###...]
Detalle de la orden de trabajo [###...]
Código [A####]
Armadora [####]
Nombre de color (20)
Detalles [1..N]
  * Formula
  * Cantidad

## Criterios de aceptación
* Dado un detalle de orden de trabajo, el sistema advierte en caso de que el detalle ya se encuentre asociado a una planilla de pintura.
* Dado un nuevo detalle, el sistema advierte en caso de que hayan dos iguales.

## Tareas
- [x] Crear Modelo de Datos
- [x] Crear Plantilla para asociar a la orden de trabajo
- [x] Controlador

### Gantt

GanttStart: 2021-10-27
GanttDue: 2021-11-02

**Comment by Pazitos10** [comment]
Con respecto a los datos, creo que si se tiene acceso al detalle de la orden de trabajo, el número de orden ya no es necesario porque un detalle de OT pertenece solo a una OT.
Si _Detalles_ hace referencia a detalles de la planilla de pintura, sólo modificaría el nombre de ese campo así queda más claro. Por ej,: _Detalles de planilla de pintura_ (similar a #4)
Luego, en relación a los criterios no me queda claro el 2do. Asumo que hacen referencia a un detalle de la planilla por lo que les recomendaría que lo desarrollen un poco más.
