### ISSUE TITLE
[1pt] Registrar Ingreso de Vehiculo

### ISSUE THREAD

**Issue by murillo6** [UNPSJB/TallerChaPin#16]
Como Administrativo quiero dar el ingreso al vehículo al taller para imprimir la orden de trabajo

### Datos
***Dominio de vehículo***

## Criterios de Aceptación
* Dado que el Cliente  no posee turno para el día, se rechaza la aceptación de su Vehículo
* Dado que el dominio del Vehículo no sea el del turno se rechaza la aceptación del mismo

### Tareas
- [x] Rafactor Model
- [x] Plantilla
- [x] Controlador

### Gantt

GanttStart: 2021-10-07
GanttDue: 2021-10-08

**Comment by Pazitos10** [comment]
@murillo6 similar a #18, falta el "para" en la introducción. Además, los criterios de aceptación involucran al Cliente y una Fecha quizás sea necesario añadir esos datos a la lista de esta HU.
