### ISSUE TITLE
Registro de Tarea

### ISSUE THREAD

**Issue by murillo6** [UNPSJB/TallerChaPin#18]
Como Empleado quiero registra la realizacion de una tarea en la orden de trabajo 

### Datos
***Nombre***(30)

## Criterios de Aceptación

**Comment by Pazitos10** [comment]
@murillo6 a la introducción le falta el "para" (ver ejemplo en la pestaña "Projects"-> tablero "Backlog" y/o teoría), en donde se expresa el valor que agrega contar con esta característica y por qué se debería implementar esta historia de usuario.
Además, ¿qué otros datos se necesitarían para poder registrar una tarea?¿Qué criterios se deberían tener en cuenta para evaluar y potencialmente aceptar la implementación de esta HU?
