### ISSUE TITLE
Tarjetas a hacer

### ISSUE THREAD

**Issue by ramirocanario1** [UNPSJB/TallerChaPin#19]
- [x] Crear presupuesto
- [x] Confirmar presupuesto
- [x] Cancelar orden de trabajo
- [x] Ampliar presupuesto
- [x] Ver presupuestos confirmados
- [x] Facturar órden de trabajo
- [x] Cambiar turno
- [x] Registrar ingreso de vehículo
- [x] Registrar inicio de trabajo
- [x] Registrar fin de trabajo
- [x] Confeccionar planilla de pintura
- [x] ABM tareas
- [x] ABM tipo de tarea
- [x] Registrar entrega de vehículo
- [x] Registrar tipo de pago
- [x] Registrar pago
- [x] ABM materiales
- [x] ABM repuestos
- [x] Listar repuestos
- [x] Modificar stock de materiales y repuestos
- [x] ABM Cliente
- [x] ABM Vehiculos
- [x] Listar vehículos
- [x] ABM Marca
- [x] ABM Modelo
- [x] ABM Empleado
- [x] Listar empleados
- [x] Vincular tipo de tarea con empleado
- [x] Desvincular tipo de tarea con empleado
- [x] Listar Clientes

### Gantt

GanttStart: 2021-08-11
GanttDue: 2021-12-08

**Comment by Matiaseze** [comment]
Agregue "Listar Clientes" al final
