### ISSUE TITLE
[3pt] Cancelar orden de trabajo

### ISSUE THREAD

**Issue by ramirocanario1** [UNPSJB/TallerChaPin#20]
**Como** Jefe de Taller (o Administrativo, u Oficial Pintor) **quiero** cancelar una orden de trabajo **para** que quede registrado en el sistema.

### Datos
DNI [########]
Número de presupuesto [####]

## Criterios de aceptación
* Dado un DNI que no pertenece a ningún Cliente, el sistema advierte y no permite continuar.
* Dado un nro. de presupuesto que no pertenece a ningún presupuesto, el sistema advierte y no permite continuar.
* Dado un presupuesto, el sistema advierte en caso de que no haya una orden de trabajo vinculada al mismo.
* Dado un presupuesto y un cliente, el sistema advierte en el caso en que el presupuesto no le pertenezca al cliente.
* Dada una orden de trabajo con al menos una tarea ya iniciada, el sistema lo advierte y no permite realizar la cancelación.

### Tareas
- [x] Plantilla
- [x] Controlador

### Gantt

GanttStart: 2021-10-16
GanttDue: 2021-10-22

**Comment by Pazitos10** [comment]
Modificaría el "para" de la descripción dado que me resulta un poco amplio ya que todo lo que se haga en el sistema va a quedar registrado de algún modo. 
Piensen en el motivo por el cual se necesitaría contar con esta funcionalidad en el sistema. Por ej.: "para permitir que los clientes puedan cancelar la realización de trabajos en sus vehículos"
