### ISSUE TITLE
Ver presupuestos confirmados

### ISSUE THREAD

**Issue by ramirocanario1** [UNPSJB/TallerChaPin#21]
**Como** Administrativo (o Empleado, Jefe de Taller u Oficial Pintor) **quiero** ver los presupuestos confirmados **para** generar una lista con los mismos.

### Datos
[No se requiere ningún dato para esta historia de usuario]

## Criterios de aceptación
* En el caso en que no hayan presupuestos confirmados, el sistema lo advierte mediante un mensaje en pantalla.

**Comment by Pazitos10** [comment]
Interpreto que este es un listado mas. Si es así, añádanlo al issue con los demás listados.
