### ISSUE TITLE
[1pt] Registrar entrega de vehiculo

### ISSUE THREAD

**Issue by Matiaseze** [UNPSJB/TallerChaPin#24]
## Descripción
*Como*  Administrativo/Jefe de taller/Oficial pintor/ Empleado *quiero*  registrar la entrega del vehículo *para* para dejar constancia del trabajo realizado

### Datos
***Patente del Vehículo***
**Numero de Orden de Trabajo**

## Criterios de Aceptación
* En caso de no estar la orden de trabajo abonada el sistema advierte que no se puede registrar la entrega del vehículo
* En caso de que las tareas de la orden de trabajo no estén finalizadas el sistema advierte que no se puede registrar la entrega del vehículo.
* En caso que el sistema no encuentre el vehículo el sistema advierte que no puede registrar la entrega sin un vehículo existente
* Dado un vehículo existente pero sin una orden de trabajo asociada el sistema advierte que no puede registrar la entrega del vehículo.

## Tareas
- [x] Crear Modelo de Datos
- [x] Crear Plantilla de entrega de vehículo para dejar constancia de trabajo realizado
- [x] Controlador

### Gantt

GanttStart: 2021-11-03
GanttDue: 2021-11-04

**Comment by Pazitos10** [comment]
Modificaría el "para" de la descripción, por ejemplo:  "...para dejar constancia de la finalización de un trabajo"
