### ISSUE TITLE
Registrar tipo de pago

### ISSUE THREAD

**Issue by Matiaseze** [UNPSJB/TallerChaPin#25]
## Descripción
*Como* Administrativo *quiero* añadir datos de un nuevo medio de pago *para*  para ofrecer diferentes formas de pago al cliente

### Datos
**Nombre tipo de pago**

## Criterios de Aceptación
* Dado un Nombre de un tipo pago igual a otro Nombre tipo de pago existente el sistema advierte que el tipo de pago existe

**Comment by Pazitos10** [comment]
Modificaría el "para" de la descripción. Algo así como: "para ofrecer diferentes formas de pago al cliente" o similar

**Comment by diegomvh** [comment]
El tipo de pago requiere de un Registrar? No estamos en situación de crear una estructura para algo que solo van a ser 3 o 4 instancias? "efectivo, con tarjeta de débito, con tarjeta de crédito o crédito personal" ?

**Comment by Pazitos10** [comment]
Estaría faltando asignarle un puntaje y acomodarla en el tablero dentro de alguno de los sprints.
