### ISSUE TITLE
[2pt] Registrar Pago

### ISSUE THREAD

**Issue by Matiaseze** [UNPSJB/TallerChaPin#26]
## Descripción
*Como* Administrativo *quiero* concretar la facturación de las reparaciones hechas al vehículo de un cliente *para*  registrar el pago en el sistema. 

### Datos
***DNI***
***Patente del vehículo***
Tipo de pago

## Criterios de Aceptación
* Dado un DNI que no pertenezca a un cliente el sistema advierte que no se encontró el cliente
* Dado una Patente que no pertenezca a un vehículo asociado al cliente con DNI en el sistema el sistema advierte que no encontró el vehículo
* Dado un vehículo cuya orden de trabajo tenga tareas sin terminar, el sistema advierte que no se puede registrar el pago
* Dada una orden de trabajo vinculada al vehículo que ya se encuentra registrado su pago el sistema advierte que no se puede registrar el pago

### Tareas
- [x] Modelo
- [x] Plantilla
- [x] Controlador
- [x] Diseñar recibo

### Gantt

GanttStart: 2021-11-06
GanttDue: 2021-11-09

**Comment by Pazitos10** [comment]
Una salvedad con respecto a la patente. "Dado una Patente que no pertenezca a un vehiculo asociado al cliente con DNI en el sistema ...". En esencia es la misma idea pero harían el control un poco más restrictivo.
