### ISSUE TITLE
[2pt] Listados

### ISSUE THREAD

**Issue by Matiaseze** [UNPSJB/TallerChaPin#28]
### Listar clientes
- *Filtros*
Nombre y apellido (cliente)
DNI (cliente)

- *Datos que se mostraran*
Nombre y apellido (cliente)
DNI (cliente)
Teléfono (cliente)

### Listar vehículos
- *Filtros*
Patente (vehículo)
Marca (vehículo)
Modelo (vehículo)
Estado (vehículo)

- *Datos que se mostraran*
Patente (vehículo)
Marca (vehículo)
Modelo (vehículo)
Estado (vehículo)

### Listar Repuestos
- *Filtros*
Marca (repuesto)
Tipo de repuesto (repuesto)

- *Datos que se mostraran*
Marca(repuesto)
Tipo de repuesto (repuesto)
Cantidad (repuesto)
Precio unitario (repuesto)

### Listar empleados
- *Filtros*
Legajo (empleado)
Nombre y apellido (empleado)

- *Datos que se mostraran*
Nombre y apellido (empleado)
Legajo (empleado)
CUIL (empleado)

### Listado de presupuestos
- *Filtros*
Numero de presupuesto (presupuesto)
Estado (orden de trabajo)

- *Datos que se mostraran*
Numero de presupuesto (presupuesto)
Fecha realizado (presupuesto)
Monto total (presupuesto)

### Tareas
- [x] Diseñar plantilla
- [x] Controlador

### Gantt

GanttStart: 2021-11-04
GanttDue: 2021-11-06

**Comment by Pazitos10** [comment]
Faltaría añadir el puntaje y asignar la tarjeta a alguno de los sprints (probablemente el 3ro)
