### ISSUE TITLE
[1pt] Modificar stock de Material/Repuesto

### ISSUE THREAD

**Issue by Matiaseze** [UNPSJB/TallerChaPin#33]
### Descripcion
 *Como* Administrador *quiero* realizar un cambio manual en la cantidad de stock de materiales o repuestos *para* que coincidan con las dependencias actuales en stock de materiales y repuestos
### Datos
**Material**
**Repuesto**
### Criterios de Aceptacion
* En caso de ingresar numeros negativos en los valores de la cantidad en repuestos o materiales el sistema advierte que no se puede realizar la modificacion de stock.
### Tareas
- [x] Plantilla
- [x] Controlador

### Gantt

GanttStart: 2021-11-08
GanttDue: 2021-11-09

**Comment by ramirocanario1** [comment]
Este issue está relacionado con el bug de #53
