### ISSUE TITLE
[1pt] ABM Tipo Material

### ISSUE THREAD

**Issue by diegomvh** [UNPSJB/TallerChaPin#35]
## Descripción
*Como* Administrativo *quiero* registrar/modificar un tipo de material *para* incluirlo en un presupuesto u orden de trabajo.

## Datos
**Nombre** (40)
Unidad de medida 

### Alta
* Dado un tipo de material con el mismo nombre cuando confirmo el alta el sistema advierte tipo de material ya existe.

### Modificar
* Dado un tipo de material con el mismo nombre que no sea el mismo al confirmar el sistema advierte tipo de material existe.

### Baja
* Dada un material o materiales asociado/s al tipo de material cuando elimino el sistema advierte no se puede eliminar el tipo de material.

## Ejemplos
Nombre: Lija, Masilla, Pintura, Praimer
Unidad de medida: Lts, Kg, Gr, mL

### Tareas
- [x] Modelo 
- [x] Plantilla
- [x] Controlador

### Gantt

GanttStart: 2021-09-28
GanttDue: 2021-09-29

**Comment by ramirocanario1** [comment]
El bug está relacionado con el issue #56
