### ISSUE TITLE
Error al hacer varios clicks en los encabezados de listados

### ISSUE THREAD

**Issue by ramirocanario1** [UNPSJB/TallerChaPin#57]
Hice algunos clicks en el encabezado de la columna de "Repuestos?" en el listado de tipos de tarea y me saltó un error. Seguí probando y no volvió a aparecer.

![image](https://user-images.githubusercontent.com/57329496/170838185-2190d142-21e2-4d31-b97f-3a828da422dd.png)

**Comment by Matiaseze** [comment]
![image](https://user-images.githubusercontent.com/51457471/191889940-13850c61-11d9-499b-bff3-6c26b3b292e5.png)
Encontre otro

**Comment by Matiaseze** [comment]
Esto se resolvió en el commit 394 (falto aclararlo en el mismo)
