### ISSUE TITLE
"FieldError at /ordenes/orden/listar"

### ISSUE THREAD

**Issue by ramirocanario1** [UNPSJB/TallerChaPin#75]
![image](https://user-images.githubusercontent.com/57329496/188514688-beb03563-221e-47c1-920b-4224175b569d.png)

**Comment by Matiaseze** [comment]
![image](https://user-images.githubusercontent.com/51457471/192391377-1dba2002-0a5a-4dea-8334-c288a09e0f02.png)

**Comment by Matiaseze** [comment]
![image](https://user-images.githubusercontent.com/51457471/192391488-c504781b-da59-4515-8e9a-bf7f4935c29a.png)

**Comment by Pazitos10** [comment]
@Matiaseze, @ramirocanario1 en ambos casos el error viene de intentar aplicar un filtro sobre un determinado modelo en donde los nombres de los campos en el filtro no coinciden con campos/atributos del modelo. 
Por ejemplo: `OrdenDeTrabajo` no tiene un campo `cliente` ni `vehículo`. Algo similar ocurre con el modelo de `Material`.
En el caso de `OrdenDeTrabajo`, tanto `cliente` como `vehiculo` no son atributos de la clase sino `@property`. [Esta respuesta en stackoverflow](https://stackoverflow.com/a/31659633/3247017) explica un poco más.

Para resolverlo, en los `FiltrosForm` que corresponda, modifiquen los campos para que les permita encontrar los atributos del modelo que quieren filtrar. Por ejemplo, `OrdenDeTrabajoFiltrosForm` en lugar de `cliente` será `presupuestos__cliente`. Pueden indicarle en los atributos al campo, el label personalizado para que en el formulario no se renderice `presupuestos__cliente` sino "Cliente".
