### ISSUE TITLE
Tareas post charla 24/02

### ISSUE THREAD

**Issue by ramirocanario1** [UNPSJB/TallerChaPin#94]
- [x] Agregar unidad de medida luego de las cantidades
- [x] Listado de órdenes que tenga número y fecha
- [x] Al crear presupuesto, que solo muestre repuestos del vehículo elegido
- [x] Solucionar fechas que se guardan mal al finalizar tareas
- [x] Que se pueda elegir hora al terminar una tarea
- [x] Que la fecha maxima sea ahora al seleccionar fecha de fin de tarea

**Comment by diegomvh** [comment]
agrego detalle
